{{- if .Values.ingress.enabled -}}
{{- $serviceName := .Release.Name -}}
{{- $servicePort := .Values.service.externalPort -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $serviceName }}
  labels: 
    app: {{ template "app.name" . }}
    chart: {{ .Values.appName }}-{{ .Values.imageTag }}
    release: {{ $serviceName }}
    heritage: {{ .Release.Service }}
  annotations:
    {{- range $key, $value := .Values.ingress.annotations }}
      {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  rules:
  {{- if .Values.ingress.simpleRouting }}
    - host: {{ $serviceName }}.{{ default "c32393bdffebc495c9804aeda87b21514" .Values.clusterId  }}.{{ default "cn-beijing" .Values.regionId }}.alicontainer.com
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ $serviceName }}
              servicePort: {{ $servicePort }}
    - host: {{ $serviceName }}.{{ default "ktest.sample.com" .Values.simpleRoutingDomainSuffix }}
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ $serviceName }}
              servicePort: {{ $servicePort }}
  {{- end }}
    {{- range $host := .Values.ingress.hosts }}
    - host: {{ $host }}
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ $serviceName }}
              servicePort: {{ $servicePort }}
    {{- end -}}
  {{- if .Values.ingress.tls }}
  tls:
{{ toYaml .Values.ingress.tls | indent 4 }}
  {{- end -}}
{{- end -}}
